kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: http-echo
spec:
  containers:
  - name: foo-app
    image: ealen/echo-server:latest
    ports:
    - containerPort: 80
    env:
    - name: PORT
      value: "80"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  type: ClusterIP
  selector:
    app: http-echo
  ports:
  # Default port used by the image
  - port: 80


